package goreq

var MimeToExtensions = map[string]string{
	"text/plain":                  ".txt",
	"text/html":                   ".html",
	"text/css":                    ".css",
	"text/javascript":             ".js",
	"application/json":            ".json",
	"application/xml":             ".xml",
	"application/octet-stream":    ".bin",
	"image/jpeg":                  ".jpg",
	"image/png":                   ".png",
	"image/gif":                   ".gif",
	"image/webp":                  ".webp",
	"application/pdf":             ".pdf",
	"audio/mpeg":                  ".mp3",
	"audio/wav":                   ".wav",
	"video/mp4":                   ".mp4",
	"video/x-msvideo":             ".avi",
	"application/zip":             ".zip",
	"application/x-tar":           ".tar",
	"application/gzip":            ".gz",
	"application/x-7z-compressed": ".7z",
	"application/msword":          ".doc",
	"application/vnd.ms-excel":    ".xls",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document":   ".docx",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":         ".xlsx",
	"application/vnd.ms-powerpoint":                                             ".ppt",
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
}
