// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package course

import (
	"kd_api/api/course"
)

type ControllerV1 struct{}

func NewV1() course.ICourseV1 {
	return &ControllerV1{}
}
