// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"kd_api/internal/dao/internal"
)

// internalCourseDao is internal type for wrapping internal DAO implements.
type internalCourseDao = *internal.CourseDao

// courseDao is the data access object for table course.
// You can define custom methods on it to extend its functionality as you wish.
type courseDao struct {
	internalCourseDao
}

var (
	// Course is globally public accessible object for table course operations.
	Course = courseDao{
		internal.NewCourseDao(),
	}
)

// Fill with you ideas below.
